'use strict';var qx={TAB:0,fg:1,Xi:2},rx=function(a){cb("MediaRouter.CastStreaming.Start.Success",a,qx)};var sx=Ja("mr.mirror.cast.LogUploader"),ux=function(a,b,c){tx("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},tx=function(a,b,c,d){if(0==b.size)u(sx,"Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);uj("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;Ej(a)?(b=Fj(a),u(sx,"Upload to Crash succeeded: "+
b)):u(sx,"Upload to Crash failed. HTTP status: "+a.za());d&&d(b)},"POST",e,void 0,3E4)}};var vx=function(){this.a=0;Of(this)},xx=function(){wx||(wx=new vx);return wx},yx=function(){var a=xx(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.a&&c&&d-a.a<c?!1:Math.random()<b.fraction};vx.prototype.ea=function(){return"mirror.cast.LogUtils"};vx.prototype.ta=function(){return[void 0,{lastAutoSubmitMillis:this.a}]};vx.prototype.wa=function(){var a=Mf(this);this.a=a&&a.lastAutoSubmitMillis||0};var wx=null;Ja("mr.mirror.cast.LogUtils");var zx=Ja("mr.NetworkUtils"),Ax=function(a,b){return te?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(t(zx,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(u(zx,"TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Bx=function(){this.a=Promise.resolve(1)},Dx=function(a,b,c){return Cx(a,function(a){return a==b},c)},Ex=function(a,b){var c=[3,4];return Cx(a,function(a){return-1!=c.indexOf(a)},b)},Fx=function(a,b){a.a=a.a.catch(function(){return 1});return Cx(a,function(){return!0},b)},Cx=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.a=a.a.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new Gx(a);try{var g=c(f)}catch(y){g=
Promise.reject(y)}return g.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.a)throw Error("A prior operation that started at "+(a+" did not complete."));return f.a})},function(a){e(a);throw a;});return f},Gx=function(a){this.b=a;this.a=null},Hx=function(a,b){a.a="number"===typeof b?b:a.b};var Ix={Fp:"OFFER",Dm:"ANSWER",Yp:"PRESENTATION",Un:"GET_STATUS",Mq:"STATUS_RESPONSE",Tn:"GET_CAPABILITIES",Wm:"CAPABILITIES_RESPONSE",zq:"RPC"};var Jx=function(){this.capabilities=this.status=this.a=this.error=this.rpc=this.result=this.type=this.b=this.sessionId=null},Mx=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Kx(JSON.parse(a),function(a){b=Lx(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},Lx=function(a){var b=new Jx;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Nx(a.seqNum,function(a){b.b=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=ka(Object.keys(Ix)),e=d.next();!e.done;e=d.next())if(Ix[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(ma(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}Kx(a.error,function(a){b.error=Ox(a)},function(){throw Error('"error" must be an Object');});Kx(a.answer,function(a){b.a=Px(a)},function(){throw Error('"answer" must be an Object');});Kx(a.status,function(a){b.status=Qx(a)},function(){throw Error('"status" must be an Object');
});Kx(a.capabilities,function(a){b.capabilities=Rx(a)},function(){throw Error('"capabilities" must be an Object');});return b},Kx=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Nx=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Sx=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Tx=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Ux=function(){this.j=null;this.a=[];this.b=
[];this.f=this.g=this.h=null},Px=function(a){var b=new Ux;Nx(a.udpPort,function(a){b.j=a},function(){throw Error('"answer.udpPort" must be a number');});Sx(a.sendIndexes,function(a){b.a=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Sx(a.ssrcs,function(a){b.b=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.h=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.f=String(a.castMode));
return b},Vx=function(){this.details=this.description=this.code=null},Ox=function(a){var b=new Vx;Nx(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Kx(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Wx=function(){this.b=this.a=null},Qx=function(a){var b=new Wx;Nx(a.wifiSnr,function(a){b.a=a},function(){throw Error('"status.wifiSnr" must be a number');
});Sx(a.wifiSpeed,function(a){b.b=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Xx=function(){this.b=this.a=null},Rx=function(a){var b=new Xx;Tx(a.mediaCaps,function(a){b.a=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.b=a.map(function(a){var b;Kx(a,function(a){b=Yx(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},Zx=function(){this.f=this.m=this.h=this.j=this.w=this.a=this.u=this.b=this.initDataTypes=this.g=null},Yx=function(a){var b=new Zx;"keySystemName"in a&&(b.g=String(a.keySystemName));Tx(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Tx(a.codecs,function(a){b.b=a},function(){throw Error('"capabilities.codecs" must be an array');});Tx(a.secureCodecs,function(a){b.u=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Tx(a.audioRobustness,function(a){b.a=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Tx(a.videoRobustness,function(a){b.w=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.h=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.f=String(a.distinctiveIdentifierSupport));return b};var $x=function(a){this.l=Ja("mr.mirror.cast.MessageDispatcher");this.g=a;this.a=null;this.b=new Map;this.f=0},ay=function(a,b,c){if(a.b.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.b.set(b,c);a.f=0;v(a.l,"Added subscriber for "+b+"-type messages.");a.a||(a.a=yr(a.g),a.a.onMessage=a.j.bind(a))},by=function(a,b){a.b.delete(b)&&v(a.l,function(){return"Removed subscriber of "+b+"-type messages."});0==a.b.size&&a.a&&(a.a.sa(),a.a=null)};
$x.prototype.sendMessage=function(a){return this.a?"RPC"==a.type?this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var cy=function(a,b,c,d,e){var f=null,g=function(){by(a,c);null!=f&&(clearTimeout(f),f=null)};try{ay(a,c,function(a){e(a)&&g()})}catch(l){e(null,l);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){g();e(null,a)})};
$x.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=Mx(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.b.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.f?t(this.l,b):v(this.l,b);++this.f}};var dy=chrome.cast.streaming,fy=function(a,b,c,d,e){this.T=a.sessionId;this.w=a.Le;this.G=a.Me;this.f=b;this.J=c;this.B=d;this.H=ey(e,"onAnswer",this.w);this.K=ey(e,"onSessionStop",this.w);this.l=Ja("mr.mirror.cast.StreamingLaunchWorkflow");this.s=new Bx;this.m=this.v=this.u=this.b=this.a=this.h=this.j=this.g=null};
fy.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof gy,f=b instanceof gy;(e&&b&&!f||f&&a&&!e)&&Cb("Mixing remoting and non-remoting tracks");return Dx(this.s,1,function(e){d.g=a;d.j=b;d.h=c;u(d.l,function(){return"Launching streaming for "+hy(d)+" "+("to a "+d.G+".")});return iy(d).then(d.A.bind(d)).then(function(a){return jy(d,a).then(function(b){d.H();var c=ky(d,b,a);d.a=ly(d,d.a,c);d.b=ly(d,d.b,c);if(!d.a&&!d.b)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.v=!!b.g;d.m=function(a,b){a==d.a?d.h.sc("Audio stream (id="+a+") error: "+b):a==d.b&&d.h.sc("Video stream (id="+a+") error: "+b)};dy.rtpStream.onError.addListener(d.m);return my(d,b,c)})}).then(function(){u(d.l,function(){return"Launched streaming for "+hy(d)});d.h.wd(d);Hx(e,2);return{Dg:null!=d.a?d.a.toString(16):null,li:null!=d.b?d.b.toString(16):null}})})};
fy.prototype.stop=function(){var a=this;return Fx(this.s,function(b){if(!a.g&&!a.j)return Hx(b,1),Promise.resolve();u(a.l,function(){return"Stopping streaming for "+hy(a)+"."});a.m&&(dy.rtpStream.onError.removeListener(a.m),a.m=null);if(a.h){var c=a.h.Vd();a.h=null}else c=Promise.resolve();return c.then(function(){a.a&&(dy.rtpStream.stop(a.a),dy.rtpStream.destroy(a.a),a.a=null);a.b&&(dy.rtpStream.stop(a.b),dy.rtpStream.destroy(a.b),a.b=null);a.u&&(dy.udpTransport.destroy(a.u),a.u=null);a.K();u(a.l,
function(){return"Stopped streaming for "+hy(a)+"."});a.g=null;a.j=null;Hx(b,1)})})};
var ny=function(a,b){var c=JSON.stringify(b);return Promise.all([a.a&&new Promise(function(b){return dy.rtpStream.getRawEvents(a.a,c,b)}),a.b&&new Promise(function(b){return dy.rtpStream.getRawEvents(a.b,c,b)})]).catch(function(b){a.l.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},oy=function(a){return Promise.all([a.a&&new Promise(function(b){return dy.rtpStream.getStats(a.a,b)}),a.b&&
new Promise(function(b){return dy.rtpStream.getStats(a.b,b)})]).catch(function(b){a.l.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[].concat([{}],ma(a.filter(function(a){return!!a}))))})},hy=function(a){if(a.g&&a.j)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.j)b="video-only ";else return"stopped";return a.g instanceof gy||a.j instanceof gy?b+"remoting":b+"streaming"},iy=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(dy.rtpStream.destroy(c),c=null);e&&!a.j&&(dy.rtpStream.destroy(e),e=null);u(a.l,function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.a=c;a.b=e;a.u=f;b()};a.g instanceof gy||a.j instanceof gy?dy.session.create(null,null,c):dy.session.create(a.g,a.j,c)})};
fy.prototype.A=function(){for(var a=Ru(),b=Ru(),c=[],d=ka([this.a,this.b]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.a,g=f?127:96,l=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,r=f?48E3:9E4,y=ka(dy.rtpStream.getSupportedParams(e)),z=y.next();!z.done;z=y.next())z=z.value,z.payload.payloadType=g,z.payload.maxLatency=this.f.maxLatencyMillis,z.payload.minLatency=this.f.minLatencyMillis,z.payload.animatedLatency=this.f.animatedLatencyMillis,z.payload.ssrc=
l,z.payload.clockRate=r,z.payload.aesKey=a,z.payload.aesIvMask=b,f?(z.payload.channels=2,z.payload.maxBitrate=this.f.audioBitrate,z.payload.maxFrameRate=100):(z.payload.minBitrate=this.f.minVideoBitrate,z.payload.maxBitrate=this.f.maxVideoBitrate,z.payload.maxFrameRate=this.f.maxFrameRate),c.push(new py(e,z));return c};
var ly=function(a,b,c){b&&!c.some(function(a){return a.ld==b})&&(t(a.l,"Destroying RTP stream not selected by the receiver: id="+b),dy.rtpStream.destroy(b),b=null);return b},jy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,l={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.f.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.f.dscpEnabled&&(l.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(l,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(l,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.f.maxWidth,height:a.f.maxHeight}]});e.push(l)}var r=a.g instanceof gy||a.j instanceof gy?"remoting":"mirroring",y={type:"OFFER",sessionId:a.T,seqNum:Oj(a.J),offer:{castMode:r,receiverGetStatus:!0,supportedStreams:e}};u(a.l,function(){return"Sending OFFER message: "+JSON.stringify(y)});cy(a.B,y,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.a){if(b.b!=y.seqNum)return t(a.l,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.a.f)&&e!=r||!e&&"mirroring"!=r)&&a.l.error("Expected receiver to ANSWER with castMode="+r+", but got: "+e);v(a.l,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.a)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},ky=function(a,b,c){if(b.a.length!=b.b.length)return a.l.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.a.length;e={candidate:e.candidate},++f){var g=b.a[f];if(0>g||g>=
c.length)return a.l.error("Receiver selected invalid index ("+g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[g];if(d.some(function(a){return function(b){return b.ld==a.candidate.ld}}(e)))return a.l.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.b[g];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.l.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},my=function(a,b,c){var d=null,e=function(){d&&(dy.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,g){var f=b.j||2344;u(a.l,function(){return"Starting RTP streams to receiver at "+(a.w+":"+f)+(" for selected offers: "+JSON.stringify(c))});var r=a.u||-1;a.f.dscpEnabled&&(u(a.l,"Enabled DSCP in sender."),dy.udpTransport.setOptions(r,{DSCP:!0}));dy.udpTransport.setDestination(r,{address:a.w,port:f});var y=new Set(c.map(function(a){return a.ld}));
d=function(a){y.delete(a);0==y.size&&e()};dy.rtpStream.onStarted.addListener(d);for(var r=ka(c),z=r.next();!z.done;z=r.next())z=z.value,dy.rtpStream.toggleLogging(z.ld,a.f.enableLogging),dy.rtpStream.start(z.ld,z.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},ey=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.l.error("Error from testHooks."+b,e)}}:function(){}},py=function(a,b){this.ld=
a;this.params=b},gy=function(){};var ry=function(a,b,c,d,e,f){b=Math.floor(16777216*Math.random()).toString(16);b="000000".substring(b.length)+b;var g=a.mediaSource.replace("urn:x-org.chromium.media:source:tab:","urn:x-org.chromium.media:source:tab_content_remoting:");b=Mj("undefined","cast",b,g,!0,a.description,a.iconUrl);b.forDisplay=!1;b.offTheRecord=a.offTheRecord;b.pb=a.pb;this.v=b;this.s=new fy(this.v.pb,c,d,e,f);this.m=e;this.g=new Bx;this.b=new qy;this.l=Ja("mr.mirror.cast.MediaRemoter");this.a=this.j=this.h=this.f=this.u=
null};h=ry.prototype;h.start=function(a,b){var c=this;return Dx(this.g,1,function(d){c.u=a;c.f=b;c.h=qp(c);Hx(d,2);return Promise.resolve()})};h.stop=function(){var a=this;return Fx(this.g,function(b){rp(a);a.a=null;var c=a.j;a.j=null;a.h=null;a.f=null;a.u=null;return new Promise(function(d){window.setTimeout(function(){sy(a).then(function(){Hx(b,1);d();c&&c()})},250)})})};h.Eb=function(){return this.v};
h.kl=function(a){var b=this;v(this.l,function(){return"Processing control message: "+a});var c=a.split(":"),d=(c.find(function(a){return a.startsWith("session=")})||"").substring(8);if(0==d.length)return this.l.error("Missing valid 'session' field in control message: "+a),Promise.resolve();switch(c[0]){case "START_CAST_REMOTING":return ty(this,d).catch(function(a){b.l.error("Failed to start remoting",a);uy(b,d)});case "START_CAST_REMOTING_STREAMS":var e=c.some(function(a){return"audio=Y"==a}),c=c.some(function(a){return"video=Y"==
a});return vy(this,d,e,c).then(this.w.bind(this)).catch(function(a){b.l.error("Failed to start remoting streams",a);uy(b,d)});case "STOP_CAST_REMOTING":return wy(this,d).then(function(){b.w("STOPPED_CAST_REMOTING:session="+d)}).catch(function(a){b.l.error("Failed to stop remoting",a);uy(b,d)});default:this.l.error("Unknown control message: "+a)}return Promise.resolve()};h.Ql=function(a){return xy(this.b,a)};h.wd=function(a){this.f&&this.f.wd(a)};h.Vd=function(){return this.f?this.f.Vd():Promise.resolve()};
h.sc=function(a,b){this.l.error("Error during streaming: "+a,b);null!=this.a&&uy(this,this.a)};
var ty=function(a,b){if(null!=a.a)return Promise.reject(Error("Attempt to start a second session ("+b+") during existing session ("+a.a+")."));a.a=b;var c=!1;u(a.l,function(){c=!0;return"Starting next media remoting session (id="+b+")."});c&&yy(a.b,function(b){return u(a.l,b)});zy(a.b);return Dx(a.g,2,function(b){return(0,a.u)().then(function(c){a.j=c;ay(a.m,"RPC",function(b){if(b.rpc){var c=a.b;b=b.rpc;c.h&&(++c.m,c.b+=b.length,c.h(b))}});Hx(b,3)}).catch(function(c){return sy(a).then(function(){Hx(b);
throw c;})})})},vy=function(a,b,c,d){return a.a!=b?Promise.reject(Error("Cannot start streams for an unknown session ("+b+") during existing session ("+a.a+")")):Dx(a.g,3,function(e){return a.s.start(c?new gy:null,d?new gy:null,a).then(function(c){var d="STARTED_CAST_REMOTING_STREAMS:session="+b;c.Dg&&(d+=":audio_stream_id="+c.Dg);c.li&&(d+=":video_stream_id="+c.li);Ay(a.b,function(b){return a.m.sendMessage(b)},function(b){var c=a.h;c.a&&c.a(b)});Hx(e,4);return d}).catch(function(b){return sy(a).then(function(){Hx(e);
throw b;})})})},wy=function(a,b){if(a.a!=b)return Promise.reject(Error("Attempting to stop an unknown session ("+b+") during existing session ("+a.a+")."));a.a=null;return new Promise(function(b,d){Ex(a.g,function(c){return sy(a).then(function(){Hx(c,5);(0,a.j)().then(function(){return Dx(a.g,5,function(a){Hx(a,2);return Promise.resolve()})}).then(b,function(a){return d(a)});a.j=null})}).catch(function(a){return d(a)})})},sy=function(a){return a.s.stop().then(function(){by(a.m,"RPC");By(a.b);Cy(a.b)})};
ry.prototype.w=function(a){this.h?(v(this.l,function(){return"Sending control message to browser: "+a}),sp(this.h,a)):v(this.l,function(){return"Dropping control message to browser: "+a})};
var uy=function(a,b){a.w("FAILED_CAST_REMOTING:session="+b);a.stop()},op=function(){return bx(Re.get("mr.ProviderManager")||null,"cast")},qy=function(){this.h=this.j=this.a=null;this.w=this.b=this.m=this.f=this.u=0;this.g=null},zy=function(a){a.a=[];Dy(a,performance.now())},Ay=function(a,b,c){a.j=b;a.h=c;a.a?(b=a.a,a.a=null,b.forEach(function(b){return xy(a,b.data).then(b.Sl,b.Rh)})):Dy(a,performance.now())},By=function(a){if(a.a){var b=Error("Stop before delivering pending message");a.a.forEach(function(a){return a.Rh(b)});
a.a=null}a.j=null;a.h=null},xy=function(a,b){if(a.j){var c=btoa(String.fromCharCode.apply(null,b));++a.u;a.f+=b.length;return a.j({type:"RPC",rpc:c})}return a.a?new Promise(function(c,e){a.a.push({data:b,Sl:c,Rh:e})}):Promise.reject(Error("RPC pipe not started"))},yy=function(a,b){Cy(a);a.g=setInterval(function(){if(a.a)var c=a.a.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.w)/1E3,d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.f/d)+
" bytes/sec) and ")+("received "+a.m+" messages ("+Math.round(a.b/d)+" ")+"bytes/sec).";Dy(a,c);c=d}b(c)},3E4)},Cy=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},Dy=function(a,b){a.u=0;a.f=0;a.m=0;a.b=0;a.w=b};var Ey=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Fy=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Gy=function(a,b,c,d,e){this.f=new fy(a,b,c,d,void 0===e?null:e);this.l=Ja("mr.mirror.cast.MediaStreamer");this.j=new Bx;this.g=this.b=this.a=this.h=null};Gy.prototype.start=function(a,b){var c=this;return Dx(this.j,1,function(d){c.h=a;c.a=Ey(a);c.a&&"ended"==c.a.readyState&&(c.a=null);c.b=Fy(a);c.b&&"ended"==c.b.readyState&&(c.b=null);if(!c.a&&!c.b)return Hx(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.f.start(c.a,c.b,c.g).then(function(){return Hx(d,2)})})};
Gy.prototype.stop=function(){var a=this;return Fx(this.j,function(b){return a.f.stop().then(function(){a.a=null;a.b=null;a.h=null;a.g=null;Hx(b,1)})})};var Hy=function(a){return Dx(a.j,2,function(b){u(a.l,"Suspending media streaming...");return a.f.stop().then(function(){u(a.l,"Suspended media streaming.");Hx(b,3)})})};
Gy.prototype.resume=function(){var a=this;return Dx(this.j,3,function(b){a.a&&"ended"==a.a.readyState&&(a.a=null);a.b&&"ended"==a.b.readyState&&(a.b=null);if(!a.a&&!a.b)return Promise.reject(Error("Cannot resume: All tracks have ended."));u(a.l,"Resuming media streaming...");return a.f.start(a.a,a.b,a.g).then(function(){u(a.l,"Resumed media streaming.");Hx(b,2)})})};var Iy=function(a,b,c){this.j=a;this.g=b;this.f=c;this.l=Ja("mr.mirror.cast.WifiStatusMonitor");this.a=null;this.b=[]};Iy.prototype.start=function(){var a=this;null==this.a&&(v(this.l,"Starting Wifi Status Monitoring."),this.b=[],ay(this.f,"STATUS_RESPONSE",function(b){return Jy(a,b)}),this.a=setInterval(function(){return Ky(a)},12E4),Ky(this))};Iy.prototype.stop=function(){null!=this.a&&(v(this.l,"Stopping Wifi Status Monitoring."),clearInterval(this.a),this.a=null,by(this.f,"STATUS_RESPONSE"))};
var Jy=function(a,b){if(null!=a.a)if(b.status){var c={};null!=b.status.a&&(c.wifiSnr=b.status.a);null!=b.status.b&&(c.wifiSpeed=b.status.b[3]);0==Object.keys(c).length?t(a.l,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.b.length&&a.b.shift(),a.b.push(c),u(a.l,function(){return"Current Wifi status: "+JSON.stringify(c)}))}else t(a.l,function(){return"Ignoring response without status: "+JSON.stringify(b)})},Ky=function(a){a.f.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:Oj(a.g),get_status:["wifiSnr","wifiSpeed"]})};var Ly=function(a,b,c,d){this.B=b.Le;this.m={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:pf(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Me};this.A=c;this.v=d;this.g=this.b=this.u=this.h=this.j=this.w=this.f=null;this.a=[]};Ly.prototype.wd=function(a){null!=this.b&&clearInterval(this.b);this.f=a;this.w=Date.now();this.b=setInterval(this.s.bind(this,a),9E5)};
Ly.prototype.Vd=function(){null!=this.b&&(clearInterval(this.b),this.b=null);if(null!=this.f){var a=this.s(this.f);this.f=null;return a}return Promise.resolve()};Ly.prototype.sc=function(a,b){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.h=a():"string"===typeof a&&(this.h=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var Ny=function(a,b){return(null==a.f?Promise.resolve():a.s(a.f)).then(function(){var c=b.map(function(b){b=My(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.kd}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),kd:new Blob(d,{type:"application/json"})}});a.a=[];return c})};
Ly.prototype.s=function(a){var b=this;if(null!=this.g)return this.g;var c=Sc(this.B).then(function(c){c={receiverVersion:c.a,receiverConnected:c.g,receiverOnEthernet:c.f,receiverHasUpdatePending:c.b,receiverUptimeSeconds:c.j};Object.assign(c,b.m);var d=Date.now();Object.assign(c,{startTime:b.w,endTime:d,activity:hy(a),receiverWifiStatus:Array.from(b.v.b)});b.w=d;null!=b.j&&(Object.assign(c,{streamingErrorTime:b.j,streamingErrorMessage:b.h,streamingErrorCause:b.u}),b.j=null,b.h=null,b.u=null);return c});
return(this.g=Promise.all([c.then(function(b){return ny(a,b)}),c,oy(a)]).then(function(a){var c=ka(a);a=c.next().value;var d=c.next().value,c=c.next().value;b.a.push({events:a,kd:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.a=My(b,b.A);b.g=null}))||Promise.resolve()};
var My=function(a,b){b-=2;for(var c=[],d=a.a.length-1;0<=d;--d){b-=a.a[d].kd.size+1;if(0>b)break;c.push({events:null,kd:a.a[d].kd});if(null!=a.a[d].events){var e=a.a[d].events.size;b>=e&&(c[c.length-1].events=a.a[d].events,b-=e)}}return c.reverse()};var Oy=function(a,b,c,d){d=void 0===d?null:d;mf.call(this,b);var e=b.pb;this.w=e.sessionId;this.J=e.Le;this.A=a;this.T=d;this.l=Ja("mr.mirror.cast.Session");this.u=new Bx;this.m=new Nj("mirror.cast.SeqNumGenerator");this.h=new $x(b.id);this.j=new Gy(e,this.A,this.m,this.h,this.T);this.f=null;this.a=new Ly(a,e,c,new Iy(this.w,this.m,this.h));this.b=!1;this.s=null};la(Oy,mf);h=Oy.prototype;
h.start=function(a){var b=this;return Dx(this.u,1,function(c){var d=new Sa("MediaRouter.CastStreaming.Session.Launch");return Py(b).then(function(c){b.b=c;return b.j.start(a,b)}).then(function(){if(b.j.f.v){var a=b.a;a.m.tdlsIsOn=b.b;a.v.start();Qy(b)}else b.a.m.tdlsIsOn=b.b;d.a();b.s=new Za("MediaRouter.CastStreaming.Session.Length");Hx(c,2);return b})})};
h.stop=function(){var a=this;return Fx(this.u,function(b){a.s&&(a.s.a(),a.s=null);a.a.v.stop();return a.j.stop().then(function(){return a.f?a.f.stop():Promise.resolve()}).then(function(){a.f=null;return a.b?Ry(a):Promise.resolve()}).then(function(){a.b=!1;Hx(b,4)})})};
h.Qh=function(){var a={sessionId:this.w,seqNum:Oj(this.m),type:"PRESENTATION",icons:[]};this.B&&(a.title=this.B);this.iconUrl&&!this.v&&a.icons.push({url:this.iconUrl});u(this.l,"Sending session metadata update to receiver: "+this.w);this.h.sendMessage(a)};h.wd=function(a){this.a.wd(a)};h.Vd=function(){return this.a.Vd()};h.sc=function(a,b){this.a.sc(a,b);this.l.error(a,b);this.stop()};
var Sy=function(a,b){return Ny(a.a,b)},Py=function(a){return a.A.useTdls?Ax(a.J,!0).then(function(b){if("Connected"==b)return u(a.l,"Successfully enabled TDLS."),!0;t(a.l,"Did not enable TDLS: result="+b);return!1}).catch(function(b){t(a.l,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Ry=function(a){return Ax(a.J,!1).catch(function(b){return a.l.error("Error while turning TDLS back off",b)})},Qy=function(a){Ty(a).then(function(b){(b.a||[]).includes("video")?Uy(a):t(a.l,function(){return"Receiver incapable of Media Remoting: "+
JSON.stringify(b)})}).catch(function(b){t(a.l,"None/Invalid capabilites response. Media Remoting disabled.",b)})},Ty=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.w,seqNum:Oj(a.m)};u(a.l,function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});cy(a.h,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.b!=d.seqNum)return u(a.l,function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+
JSON.stringify(e)}),!1;v(a.l,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Uy=function(a){Dx(a.u,2,function(b){var c=a.g.pb.Me||"<UNKNOWN>";if(!c.startsWith("Chromecast"))return t(a.l,"HACK: Media Remoting disabled because the receiver model--"+('"'+c+'" according to discovery--is not a Chromecast.')),Hx(b),Promise.resolve();a.f=new ry(a.g,0,a.A,a.m,a.h,a.T);return a.f.start(a.G.bind(a),a).catch(function(b){a.l.error("Media Remoting start failed: "+
b.message,b)}).then(function(){return Hx(b)})})};Oy.prototype.G=function(){var a=this;return Dx(this.u,2,function(b){return new Promise(function(c,d){Hy(a.j).then(function(){Hx(b,3);c(a.H.bind(a))}).catch(function(b){a.sc("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
Oy.prototype.H=function(){var a=this;return Dx(this.u,3,function(b){return new Promise(function(c,d){a.j.resume().then(function(){Hx(b,2);c()}).catch(function(b){a.sc("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Vy=function(){bf.call(this,"cast_streaming")};la(Vy,bf);h=Vy.prototype;h.getName=function(){return"cast_streaming"};h.le=function(a,b){return new Oy(a,b,Math.max(20969472,9351424),null)};h.Je=function(){rx(0)};h.Ge=function(){rx(1)};h.Jf=function(){rx(2)};h.He=function(){bb("MediaRouter.CastStreaming.Session.End")};h.Ie=function(a){cb("MediaRouter.CastStreaming.Start.Failure",a,ze)};h.Od=function(){bb("MediaRouter.CastStreaming.Stream.End")};
h.af=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&yx(),e=[9351424];d&&e.push(20969472);return Sy(a,e).then(function(a){var e=a[a.length-1];a=Xf(a[0].events).catch(function(a){b.F.error("Failed to persist events Blob.",a)});d&&0<e.events.size?ux(e.events,void 0,b.Jk.bind(b)):c&&tx("stats.json",e.kd,void 0,void 0);return a})})};h.Jk=function(a){a&&(xx().a=Date.now())};
h.tf=function(a){u(this.F,"Received message to upload logs for "+a);return this.a?Sy(this.a,[20969472]).then(function(b){b=ka(b).next().value;return 0==b.events.size?"":ux(b.events,a)}):Promise.resolve(Wy(this,a))};
var Wy=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return Xf(new Blob),u(a.F,"Uploading saved logs for feedback."),ux(c,b)},Xy=new Vy;$e("mr.mirror.cast.Service",Xy);
